version: "3.7"

services: 
  database:
    image: postgres
    container_name: databaserentx
    restart: always
    ports:
      - 9876:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes: 
      - pgdata:/data/postgres

  # server:
  #   build: .
  #   container_name: rentx
  #   ports: 
  #     - 3333:3333
  #   volumes: 
  #     - .:/usr/app
  #   links: 
  #     - database
  #   depends_on: 
  #     - database

volumes: 
  pgdata:
    driver: local