name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  deploy:
    name: Upping to server
    runs-on: test
    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: docker-compose -f docker-compose.yml build --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}  --no-cache --force-rm 

      - name: Update Image
        run: docker-compose -f docker-compose.yml up -d 

      - name: Cleanup
        run: docker image prune -a -f
