name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
   deploy:
    name: Upping to server
    runs-on: test
    steps:
      - name: Deploying on test server
        uses: actions/checkout@v2
      - run: docker-compose -f docker-compose.yml build --no-cache --force-rm && docker-compose -f docker-compose.yml up -d && docker image prune -a -f
